### ISSUE TITLE
#FeatureRequest Settings for OffsetX, OffsetY, Width,

### ISSUE THREAD

**Issue by Tymski** [tmplinshi/KeypressOSD#4]
I think your software would be much more useful if it was possible to position the text window in any spot of the screen using offsetX value from the top/bottom of the screen.
The next thing would be to add width of the window as an option and offsetY.

**Comment by tmplinshi** [comment]
Yeah, can be useful. Will do this soon.

**Comment by tmplinshi** [comment]
Hi, these settings are now avalible in v2.50. :)

```
﻿v2.50 (2018-04-13) - Added offset/fixed coordinates and window width settings
                   - Added 'Suspend' item to tray menu
```

**Comment by Tymski** [comment]
That is super cool! 😄
