### ISSUE TITLE
Modifier keys don't work with mouse keys. Ignores mouse.

### ISSUE THREAD

**Issue by Tymski** [tmplinshi/KeypressOSD#5]
For example when I hold Shift and MiddleMouseButton it shows "Shift" and sometimes it blinks really quickly with "Shift + MButton".

**Comment by tmplinshi** [comment]
Well, if you uncheck "Show Single Modifier Key", the issue is gone. Does this solve your problem? Should I uncheck this option by default?

**Comment by Tymski** [comment]
Thanks.
