### ISSUE TITLE
Max hotkeys per interval exceeded

### ISSUE THREAD

**Issue by Tymski** [tmplinshi/KeypressOSD#7]
Too many hotkeys are fired when I for example Shift + MiddleMouse + Drag.

![image](https://user-images.githubusercontent.com/8183632/38628120-eb9ea6ce-3db0-11e8-8bc7-26c371456f2b.png)
https://autohotkey.com/docs/commands/_MaxHotkeysPerInterval.htm
`#MaxHotkeysPerInterval 200`

**Comment by tmplinshi** [comment]
I can't reproduce the issue, but I will add `#MaxHotkeysPerInterval 200` in the next version. Thanks!

**Comment by Tymski** [comment]
Did you try bash the keyboard really fast? :D

**Comment by tmplinshi** [comment]
Ok, I successfully reproduced the issue by doing what you said. :D
