### ISSUE TITLE
Error: Parameter #2 invalid. 

### ISSUE THREAD

**Issue by Jan02** [tmplinshi/KeypressOSD#9]
![Alt Text](https://my.mixtape.moe/ebalxi.png)

**Comment by tmplinshi** [comment]
Seems you're using an outdated version of AutoHotkey. Download the latest version here: https://autohotkey.com/download/

**Comment by Jan02** [comment]
after updating this one shows up but the script displays some of the keys
![Alt Text](https://my.mixtape.moe/pmhlhf.png)

doesn't display: 
numpad, delete, backspace, insert, home, page up/down, delete, end

**Comment by tmplinshi** [comment]
That's weird. Please download this file to test:
[KeypressOSD-master.zip](https://github.com/tmplinshi/KeypressOSD/files/2423815/KeypressOSD-master.zip)

Unpack all the files, then run **KeypressOSD.exe** (this file was renamed from AutoHotkeyU32.exe).

**Comment by Jan02** [comment]
same error

**Comment by tmplinshi** [comment]
Try [KeypressOSD-Test.ahk](https://gist.githubusercontent.com/tmplinshi/fbd514a01db723e9f96ace457464ebd0/raw/42f1d8bbbc703c2830f4b2b5c3bb421d70aff8ce/KeypressOSD-Test.ahk). I added `UseErrorLevel` option to the `Hotkey` command, it can prevent the hotkey error, however some bugs might still there for you.

**Comment by Jan02** [comment]
ok there isn't any error now but KeypressOSD-Test.ahk still doesn't detect the following
ç
à
è
é

**Comment by tmplinshi** [comment]
That's something a little difficult for me, right now I don't have the time to fix this.

Have you tried the more advanced version by marius-sucan: https://github.com/marius-sucan/KeyPress-OSD, I believe it works well for you.
